
export const actionConstants =
{
    // || LOGIN CONSTANTS ||
    SET_WHATSAPP_NUMBER: 'SET_WHATSAPP_NUMBER',



    // || CLIENT CONSTANTS ||

    OPEN_SIDENAV: 'OPEN_SIDENAV',
    CLOSE_SIDENAV: 'CLOSE_SIDENAV',

    OPEN_MESSAGE: 'OPEN_MESSAGE',
    CLOSE_MESSAGE: 'CLOSE_MESSAGE',

    VALIDATE_CLIENT_ID: 'VALIDATE_CLIENT_ID',
    SET_LIGHT_THEME: 'SET_LIGHT_THEME',
    SET_DARK_THEME: 'SET_DARK_THEME',

    SET_CURRENT_STORE: 'SET_CURRENT_STORE',
    UNSET_CURRENT_STORE: 'UNSET_CURRENT_STORE',

    SET_SEARCH: 'SET_SEARCH',
    SET_ACTIVITIES: 'SET_ACTIVITIES',
    SET_ORDER_LIST: 'SET_ORDER_LIST',
    SET_COLLECTIONS: 'SET_COLLECTIONS',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_MANUFACTURERS: 'SET_MANUFACTURERS',


}